### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by eschizoid** [uber/uReplicator#23]
```[ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.8:check (default) on project uReplicator: Some files do not have the expected license header -> [Help 1]```

**Comment by xhl1988** [comment]
What command did you run?

**Comment by eschizoid** [comment]
`mvn install`

**Comment by xhl1988** [comment]
The issue is fixed by #24

**Comment by eschizoid** [comment]
Still having problems to build master, now with the jacoco dependency:

`mvn clean package`

```
[INFO] Building uReplicator-Controller 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jacoco:jacoco-maven-plugin:jar:0.7.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] uReplicator ........................................ SUCCESS [  0.277 s]
[INFO] uReplicator-Controller ............................. FAILURE [  0.012 s]
[INFO] uReplicator-Worker ................................. SKIPPED
[INFO] uReplicator-Distribution ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.394 s
[INFO] Finished at: 2017-06-06T10:50:54-05:00
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.jacoco:jacoco-maven-plugin:0.7.6-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.jacoco:jacoco-maven-plugin:jar:0.7.6-SNAPSHOT -> [Help 1]
[ERROR]
```

**Comment by xhl1988** [comment]
Try this one: #16

**Comment by eschizoid** [comment]
thanks, working fine now :)
